apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
# Specification of deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  #  matchExpressions:
  #    - { key: app, operator: In, values: [ first-app, second-app ] }
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    # Specification of pod
    spec:
      containers:
        - name: second-node
          image: mjuyelrana/kub-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
