apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: mjuyelrana/kub-user-demo:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
#              value: "10.101.41.163"