version: "3.8"
services:
  auth:
    build: ./auth-api
    container_name: auth-api
  users:
    build: ./users-api
    container_name: users-api
    image: mjuyelrana/kub-user-demo
    ports: 
      - "8080:8080"
  tasks:
    build: ./tasks-api
    container_name: tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
    
