apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
# Specification of deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    # Specification of pod
    spec:
      containers:
        - name: second-node
          image: mjuyelrana/kub-first-app:v2
