version: "3"
services:
  auth:
    build: ./auth-api
    container_name: auth-api
    image: mjuyelrana/deployment-auth
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    container_name: users-api
    image: mjuyelrana/deployment-users
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://rana:wk4nFupsbntPbB3l@atlascluster.rqnxi4t.mongodb.net/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESSS: 'auth:3000'